language: node_js
sudo: false
node_js:
- '4.2.1'


before_install:
  - npm install -g gulp

install:
  # Install npm dependecies
  - npm install
  
# todo: should fix this to run tests with jasmine
script:
  - gulp build